{% set name = "pycapnp" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycapnp-{{ version }}.tar.gz
  sha256: 786a2e39b79e592a41e8a1eaeea6e41e2015ecb9f5b7f7c20dfc5768ba1ae077

build:
  number: 0
  entry_points:
    - capnpc-cython = capnp._gen:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - cython
    - pip
    - pkgconfig
    - python
  run:
    - python

test:
  imports:
    - capnp
  commands:
    - pip check
    - capnpc-cython --help
  requires:
    - pip

about:
  home: https://github.com/capnproto/pycapnp
  summary: A cython wrapping of the C++ Cap'n Proto library
  license: BSD-2-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - frol
